/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [BusinessEntityID]
      ,[NationalIDNumber]
      ,[LoginID]
      ,[OrganizationNode]
      ,[OrganizationLevel]
      ,[JobTitle]
      ,[BirthDate]
      ,[MaritalStatus]
      ,[Gender]
      ,[HireDate]
      ,[SalariedFlag]
      ,[VacationHours]
      ,[SickLeaveHours]
      ,[CurrentFlag]
      ,[rowguid]
      ,[ModifiedDate]
	    FROM [AdventureWorks2016].[HumanResources].[Employee]
	  WHERE BusinessEntityID IN (SELECT BusinessEntityID FROM[AdventureWorks2016].[HumanResources].[EmployeeDepartmentHistory] )
